"use strict";

// Project Euler: Problem 2: Even Fibonacci Numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

function fiboEvenSum(n) {
  let num1 = 1;
  let num2 = 2;
  let result = 0;
  while (num2 <= n) {
    if (num2 % 2 === 0) {
      result += num2;
    }
    let temp1 = num1;
    num1 = num2;
    num2 = temp1 + num2;
  }
  return result;
}
